# Generated by Django 3.0.5 on 2020-04-13 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('deadline_date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Deadline date')),
                ('priority', models.CharField(blank=True, choices=[('1', 'low priority'), ('2', 'below average priority'), ('3', 'average priority'), ('4', 'above average priority'), ('5', 'high priority')], default='1', help_text='Select a task priority (1-low and 5-high)', max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
